# Shared values
name: all-default

# EC2NodeClass specific values
ec2NodeClass:
  enabled: true
  amiFamily: AL2
  amiSelectorTerms:
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "scalex-cluster"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: "scalex-cluster"
  karpenterRole: eksctl-KarpenterNodeRole-scalex-cluster
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  blockDevice:
    deviceName: /dev/xvda
    volumeSize: 100Gi
    volumeType: gp3
    encrypted: true
    deleteOnTermination: true
  detailedMonitoring: true
  userData:
  instanceStorePolicy:

# NodePool specific values
nodePool:
  enabled: true
  labels:
  taints:
    - key: experiment-name
      value: all-default
      effect: NoSchedule
  requirements:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
    expireAfter: 720h
  limits:
    cpu: "1000"
    memory: 1000Gi
  weight: 10