# Shared values
name: ""

# EC2NodeClass specific values
ec2NodeClass:
  amiFamily: AL2
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "scalex-cluster"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: "scalex-cluster"
  karpenterRole: KarpenterNodeRole-scalex-cluster
