# Shared values
name: ""
experimentSize: "large"

# EC2NodeClass specific values
ec2NodeClass:
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "datascience-cluster"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: "datascience-cluster"
  karpenterRole: eksctl-KarpenterNodeRole-datascience-cluster
