# Shared values
name: ""

# EC2NodeClass specific values
ec2NodeClass:
  amiFamily: AL2
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "scalex-cluster"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: "scalex-cluster"
  karpenterRole: KarpenterNodeRole-scalex-cluster
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  blockDevice:
    deviceName: /dev/xvda
    volumeSize: 100Gi
    volumeType: gp3
    encrypted: true
    deleteOnTermination: true


# NodePool specific values
nodePool:
  taints:
    - key: experiment-name
      value: ""
      effect: NoSchedule
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ["t", "c", "m", "r"]
    - key: karpenter.k8s.aws/instance-cpu
      operator: Gt
      values: ["2"]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
    expireAfter: 720h
  limits:
    cpu: "1000"
    memory: 1000Gi
  weight: 10