# Shared values
name: ""
experimentSize: "large"

# EC2NodeClass specific values
ec2NodeClass:
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "scalex-cluster"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: "scalex-cluster"
  karpenterRole: KarpenterNodeRole-scalex-cluster
