apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: datascience-cluster
  region: us-west-2
  version: '1.30'
  tags:
    karpenter.sh/discovery: datascience-cluster # here, it is set to the cluster name

iam:
  withOIDC: true # required

karpenter:
  version: '0.36.2'

managedNodeGroups:
  - name: core-mng
    minSize: 1
    maxSize: 2
    desiredCapacity: 1

addons:
- name: vpc-cni
- name: coredns
- name: kube-proxy
- name: eks-pod-identity-agent
- name: aws-mountpoint-s3-csi-driver
- name: aws-ebs-csi-driver