apiVersion: v2
name: jupyterhub
description: A Helm chart for JupyterHub
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: jupyterhub
    version: 3.3.7
    repository: https://jupyterhub.github.io/helm-chart/
