jupyterhub:
  hub:
    db:
      pvc:
        storage: 50Gi
        storageClassName: gp2
    nodeSelector:
      NodePool: ""
    tolerations:
      - key: "experiment-name"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"

  proxy:
    https:
      enabled: false
      type: offload
    service:
      type: ClusterIP
    chp:
      nodeSelector:
        NodePool: ""
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"

  singleuser:
    startTimeout: 1200
    image:
      name: quay.io/jupyter/base-notebook
      tag: latest
    cpu:
      guarantee: 0.1
    memory:
      guarantee: 128M
    nodeSelector:
        NodePool: ""
    storage:
      capacity: 100Gi
      extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: ""
      extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /home/data
        readOnly: false
    serviceAccountName: ""
    allowPrivilegeEscalation: true
    extraPodConfig: # This is needed for Jovyan user running in every single pod, access the Service Account
      securityContext:
        fsGroup: 100
    extraEnv: # Sudo needed to configure the proper permissions to start the notebook instance
      GRANT_SUDO: "yes"
      NOTEBOOK_ARGS: "--allow-root"
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: "-R"
    uid: 0
    fsGid: 0
    cloudMetadata:
      blockWithIptables: false
    networkPolicy:
      enabled: true

  scheduling:
    userScheduler:
      enabled: true
      nodeSelector:
        NodePool: ""
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
    corePods:
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
    userPods:
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"

  prePuller:
    hook:
      enabled: false

  cull:
    enabled: false