jupyterhub:
  hub:
    db:
      pvc:
        storage: 50Gi
        storageClassName: gp2
    nodeSelector:
      NodePool: all-default
    tolerations:
      - key: "experiment-name"
        operator: "Equal"
        value: all-default
        effect: "NoSchedule"

  proxy:
    https:
      enabled: false
      type: offload
    service:
      type: ClusterIP
    chp:
      nodeSelector:
        NodePool: all-default
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: all-default
          effect: "NoSchedule"

  singleuser:
    startTimeout: 1200
    image:
      name: quay.io/jupyter/base-notebook
      tag: latest
    cpu:
      guarantee: 0.5
    memory:
      guarantee: 512M
    nodeSelector:
        NodePool: all-default
    storage:
      type: "static"
      static:
        pvcName: all-default
        subPath: "home/{username}"
      extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: all-default
      extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /home/data
        readOnly: false
    serviceAccountName: all-default
    allowPrivilegeEscalation: true
    extraPodConfig: # This is needed for Jovyan user running in every single pod, access the Service Account
      securityContext:
        fsGroup: 100
    extraEnv: # Sudo needed to configure the proper permissions to start the notebook instance
      GRANT_SUDO: "yes"
      NOTEBOOK_ARGS: "--allow-root"
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: "-R"
      CHOWN_EXTRA: "/home/shared"
    uid: 0
    fsGid: 0

  scheduling:
    userScheduler:
      enabled: true
      nodeSelector:
        NodePool: all-default
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: all-default
          effect: "NoSchedule"
    #podPriority:
    #  enabled: true
    #userPlaceholder:
    #  enabled: true
    #  replicas: 1
    corePods:
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: all-default
          effect: "NoSchedule"
    userPods:
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: all-default
          effect: "NoSchedule"

  prePuller:
    hook:
      enabled: false

  cull:
    enabled: false