jupyterhub:
  hub:
    db:
      pvc:
        storage: 50Gi
        storageClassName: gp2
    nodeSelector:
      NodePool: all-default
    tolerations:
      - key: "experiment-name"
        operator: "Equal"
        value: all-default
        effect: "NoSchedule"

  proxy:
    https:
      enabled: false
      type: offload
    service:
      type: ClusterIP
    chp:
      nodeSelector:
        NodePool: all-default
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: all-default
          effect: "NoSchedule"

  singleuser:
    startTimeout: 1200
    profileList:
      - display_name: Data Engineering
        description: "PySpark Notebooks"
        profile_options:
          image:
            display_name: "Image"
            choices:
              pyspark350:
                display_name: "PySpark 3.5.0 + Python 3.11"
                default: true
                kubespawner_override:
                  image: jupyter/pyspark-notebook:spark-3.5.0
              pyspark341:
                display_name: "PySpark 3.4.1 + Python 3.11"
                kubespawner_override:
                  image: jupyter/pyspark-notebook:spark-3.4.1
        kubespawner_override:
          node_selector:
            NodePool: all-default
          tolerations:
            - key: "experiment-name"
              operator: "Equal"
              value: all-default
              effect: "NoSchedule"
          cpu_guarantee: 2
          mem_guarantee: 8G
          cpu_limit: 4
          mem_limit: 8G
        cmd: null
    storage:
      type: "static"
      static:
        pvcName: all-default
        subPath: "home/{username}"
      extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: all-default
      extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /home/data
        readOnly: false
    serviceAccountName: all-default

  scheduling:
    userScheduler:
      enabled: true
      nodeSelector:
        NodePool: all-default
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: all-default
          effect: "NoSchedule"
    podPriority:
      enabled: true
    userPlaceholder:
      enabled: false
      replicas: 3
    corePods:
      nodeAffinity:
        matchNodePurpose: require
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: all-default
          effect: "NoSchedule"
    userPods:
      nodeAffinity:
        matchNodePurpose: require
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: all-default
          effect: "NoSchedule"

  prePuller:
    extraTolerations:
    hook:
      enabled: false
      nodeSelector:
        NodePool: all-default
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: all-default
          effect: "NoSchedule"

  cull:
    enabled: false