jupyterhub:
  hub:
    db:
      pvc:
        storage: 50Gi
        storageClassName: gp2
    nodeSelector:
      NodePool: ""
    tolerations:
      - key: "experiment-name"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"

  proxy:
    https:
      enabled: false
      type: offload
    service:
      type: ClusterIP
    chp:
      nodeSelector:
        NodePool: ""
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"

  singleuser:
    startTimeout: 1200
    image:
      name: jupyter/base-notebook
      tag: python-3.8.13
    cpu:
      guarantee: 0.5
    memory:
      guarantee: 512M
    nodeSelector:
        NodePool: ""
    storage:
      capacity: 100Gi
      extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: ""
      extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /home/data
        readOnly: false
    serviceAccountName: ""
    allowPrivilegeEscalation: true
    extraPodConfig:
      securityContext:
        fsGroup: 100
    extraEnv:
      GRANT_SUDO: "yes"
      NOTEBOOK_ARGS: "--allow-root"
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: "-R"
      RAY_CLUSTER: "raycluster-autoscaler-head-svc"
    uid: 0
    fsGid: 0
    cloudMetadata:
      blockWithIptables: false
    networkPolicy:
      enabled: true

  scheduling:
    userScheduler:
      enabled: false
    userPods:
      tolerations:
        - key: "experiment-name"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"

  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false
    pullProfileListImages: false

  cull:
    enabled: false