{{- if eq .Values.experimentSize "gpu-large" }}
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ .Values.name }}-gpu
spec:
  template:
    metadata:
      labels:
        NodePool: {{ .Values.name }}
    spec:
      nodeClassRef:
        name: {{ .Values.name }}
      taints:
        - key: experiment-name
          value: {{ .Values.name }}
          effect: NoSchedule
        - key: nvidia.com/gpu
          value: "true"
          effect: NoSchedule
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["g5.12xlarge"]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
    expireAfter: 720h
  limits:
    cpu: "1000"
    memory: 1000Gi
{{- end }}
