apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fsx-sc
  resources:
    requests:
      storage: 1200Gi