apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1200Gi # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  mountOptions:
    - allow-delete
    - region us-west-2
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: scalex-demo-{{ .Values.namespace }}-bucket
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # required for static provisioning
  resources:
    requests:
      storage: 1200Gi # ignored, required
  volumeName: {{ .Values.namespace }}
